/**
 * Client Sanity — Coraly blog auto-généré.
 *
 * Deux clients distincts :
 *  - Read client  (CDN, public) : utilise NEXT_PUBLIC_SANITY_PROJECT_ID pour
 *    être disponible dans les pages client-side (blog page.tsx, [slug]/page.tsx).
 *  - Write client (token requis) : utilise SANITY_PROJECT_ID + SANITY_API_TOKEN,
 *    disponible côté serveur uniquement (api/cron/generate-blog).
 *
 * Projet Sanity : voixcourses-blog (ID: vukx2jui) — créé dans GROA-122.
 * Type de document : "blogPost" (standard Groupe J, CLAUDE_SHARED.md).
 */

import { createClient, type SanityClient } from "@sanity/client";

const apiVersion = "2024-01-01";
const DOCUMENT_TYPE = "blogPost";

// ---------------------------------------------------------------------------
// Read client — lazy, cached, public CDN
// ---------------------------------------------------------------------------

let _readClient: SanityClient | null = null;

function getReadClient(): SanityClient {
  if (_readClient) return _readClient;
  // NEXT_PUBLIC_ prefix exposes the var in browser bundles.
  // Falls back to server-only SANITY_PROJECT_ID for SSR/API routes.
  const projectId =
    process.env.NEXT_PUBLIC_SANITY_PROJECT_ID ??
    process.env.SANITY_PROJECT_ID;
  if (!projectId) {
    throw new Error(
      "[sanity] NEXT_PUBLIC_SANITY_PROJECT_ID is not configured — " +
        "add it to Doppler and to Vercel env (NEXT_PUBLIC prefix required for client-side reads)"
    );
  }
  _readClient = createClient({
    projectId,
    dataset: process.env.SANITY_DATASET ?? "production",
    apiVersion,
    useCdn: true,
  });
  return _readClient;
}

// ---------------------------------------------------------------------------
// Write client — server-side only, no caching (token must stay secret)
// ---------------------------------------------------------------------------

function getWriteClient(): SanityClient {
  const projectId = process.env.SANITY_PROJECT_ID;
  if (!projectId) {
    throw new Error("[sanity] SANITY_PROJECT_ID is not configured");
  }
  const token = process.env.SANITY_API_TOKEN;
  if (!token) {
    throw new Error(
      "[sanity] SANITY_API_TOKEN is not configured — " +
        "add the write token (editor role) in Doppler"
    );
  }
  return createClient({
    projectId,
    dataset: process.env.SANITY_DATASET ?? "production",
    apiVersion,
    token,
    useCdn: false,
  });
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Modèle d'un article de blog tel que stocké dans Sanity. */
export interface SanityPost {
  _id: string;
  title: string;
  slug: { current: string };
  publishedAt: string;
  excerpt: string;
  /** Corps de l'article en Portable Text */
  body: unknown[];
  topicId: number;
  topicSlug: string;
  category: "accessibilite" | "formation" | "technologie" | "pratique";
  /** Temps de lecture estimé en minutes */
  readingTimeMinutes: number;
  autoGenerated: boolean;
}

// GROQ projection shared between list and single-post queries
const POST_PROJECTION = `{
  _id,
  title,
  slug,
  publishedAt,
  excerpt,
  body,
  topicId,
  topicSlug,
  category,
  readingTimeMinutes,
  autoGenerated
}`;

// ---------------------------------------------------------------------------
// Public read functions
// ---------------------------------------------------------------------------

/**
 * Récupère tous les articles publiés, triés par date décroissante.
 * Utilisé par /blog (Server Component ou useEffect client-side avec ISR).
 */
export async function getAllPosts(): Promise<SanityPost[]> {
  return getReadClient().fetch<SanityPost[]>(
    `*[_type == "${DOCUMENT_TYPE}" && defined(publishedAt)] | order(publishedAt desc) ${POST_PROJECTION}`
  );
}

/**
 * Récupère un article par son slug.
 * Utilisé par /blog/[slug].
 */
export async function getPostBySlug(slug: string): Promise<SanityPost | null> {
  const result = await getReadClient().fetch<SanityPost | null>(
    `*[_type == "${DOCUMENT_TYPE}" && slug.current == $slug && defined(publishedAt)][0] ${POST_PROJECTION}`,
    { slug }
  );
  return result ?? null;
}

// ---------------------------------------------------------------------------
// Write function — server-side only (cron)
// ---------------------------------------------------------------------------

/**
 * Publie un article généré par le cron.
 * Doit être appelé uniquement depuis des API routes / server actions.
 *
 * @returns L'ID Sanity de l'article créé.
 */
export async function publishPost(
  post: Omit<SanityPost, "_id" | "autoGenerated">
): Promise<string> {
  const client = getWriteClient();
  const result = await client.create({
    _type: DOCUMENT_TYPE,
    ...post,
    autoGenerated: true,
  });
  return result._id;
}
